#! /bin/bash

rm -f out/* aux_log/*

rk64_devices_list="
rk3328-rock64
rk3399-rockpro64
rk3399-pinebook-pro
"

rk64_devices_list_emmc="
rk3328-rock64
rk3399-rockpro64
rk3399-pinebook-pro
"

export SOLUTION=rk64-base
for i in $rk64_devices_list
do
	# STUB_TARBALL environment variable is needed
	rm -rf .ciel resolved.conf.backup
	ciel init
	ciel load-os "$STUB_TARBALL"
	# Workaround
	cp .ciel/container/dist/etc/systemd/resolved.conf resolved.conf.backup
	cat > .ciel/container/dist/etc/systemd/resolved.conf << EOF
[Resolve]
DNS=114.114.114.114
DNSSEC=no
EOF
	if [ "$MIRROR" ]; then
		ciel switchmirror "$MIRROR"
	fi
	DEVICE_NAME=$i ciel generate rk64-base
	if [ "$MIRROR" ]; then
		ciel switchmirror origin
	fi
	ciel down
	cp resolved.conf.backup .ciel/container/dist/etc/systemd/resolved.conf 
	TARBALL=temp.tar COMPRESSOR=cat ciel release rk64_base_$i
	TARBALL=$PWD/temp.tar DEVICE_NAME=$i ./raw-image-builder
	if echo "$rk64_devices_list_emmc" | grep "^$i\$"; then
		TARBALL=$PWD/temp.tar DEVICE_NAME=$i MMC=1 ./raw-image-builder
	fi
	rm temp.tar*
	for j in out/*.img # Uncompressed ones
	do
		lz4 < $j > $j.lz4 && rm $j
		for k in md5 sha1 sha512
		do
			${k}sum $j.lz4 | awk '{print $1}' > $j.lz4.${k}sum
		done
	done
done

rm -f resolved.conf.backup
