#! /bin/bash -e

rk64_devices_list="
rk3328-rock64
rk3399-rockpro64
rk3399-pinebook-pro
"

rk64_devices_list_emmc="
rk3328-rock64
rk3399-rockpro64
rk3399-pinebook-pro
"

distro_variants="
base
cinnamon
gnome
kde
lxde
mate
server
xfce
"

for i in $distro_variants; do
	export SOLUTION=rk64-$i
	for j in $rk64_devices_list; do
		aoscbootstrap \
		stable ${i}-${j} ${REPO:-https://repo.aosc.io/debs} \
		--config /usr/share/aoscbootstrap/config/aosc-mainline.toml \
		-x \
		--arch ${ARCH:-$(dpkg --print-architecture)} \
		-s \
			/usr/share/aoscbootstrap/scripts/reset-repo.sh \
			/usr/share/aoscbootstrap/scripts/enable-nvidia-drivers.sh \
			/usr/share/aoscbootstrap/scripts/enable-dkms.sh \
			/usr/share/aoscbootstrap/scripts/livekit.sh \
		--include-files /usr/share/aoscbootstrap/recipes/rk64/${i}-${j}.lst \
		-m bsp-rk

		tar cvf ${i}-${j}.tar ${i}-${j}

		TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j ./raw-image-builder
		if echo "$rk64_devices_list_emmc" | grep "^$j\$"; then
			TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j MMC=1 ./raw-image-builder
		fi

		rm -r ${i}-${j}.tar ${i}-${j}

		for k in out/*.img; do
			lz4 < $k > $k.lz4 && rm $k
			sha256sum $k.lz4 > ${k}.lz4.sha256sum
		done
	done
done
