#! /bin/bash -e

rk64_devices_list="
rk3328-rock64
rk3399-rockpro64
rk3399-pinebook-pro
"

rk64_devices_list_emmc="
rk3328-rock64
rk3399-rockpro64
rk3399-pinebook-pro
"

distro_variants="
base
cinnamon
gnome
kde
lxde
mate
server
xfce
"

for i in $distro_variants; do
	export SOLUTION=rk64-$i
	for j in $rk64_devices_list; do
		echo "Generating distribution ..."
		aoscbootstrap \
			stable ${i}-${j} ${REPO:-https://repo.aosc.io/debs} \
			--config /usr/share/aoscbootstrap/config/aosc-mainline.toml \
			-x \
			--arch ${ARCH:-$(dpkg --print-architecture)} \
			-s \
				/usr/share/aoscbootstrap/scripts/reset-repo.sh \
				/usr/share/aoscbootstrap/scripts/enable-nvidia-drivers.sh \
				/usr/share/aoscbootstrap/scripts/enable-dkms.sh \
				/usr/share/aoscbootstrap/scripts/rawimage.sh \
			--include-files /usr/share/aoscbootstrap/recipes/rk64/${i}-${j}.lst \
			-m bsp-rk

		echo "Creating distribution tarball ..."
		tar cvf ${i}-${j}.tar ${i}-${j}

		echo "Generating raw image ..."
		TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j ./raw-image-builder
		if echo "$rk64_devices_list_emmc" | grep "^$j\$"; then
			echo "Generating raw image (MMC) ..."
			TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j MMC=1 ./raw-image-builder
		fi

		echo "Removing generated distributions ..."
		rm -r ${i}-${j}.tar ${i}-${j}
	done
done

for i in out/*.img; do
	echo "Compressing $i ..."
	lz4 -9 -vvv < $i > $i.lz4 && rm $i

	echo "Creating checksum for $i ..."
	sha256sum $i.lz4 > ${i}.lz4.sha256sum
done
