#!/bin/bash -e

rpi64_devices_list="
rpi-3b
rpi-cm3
rpi-4b
rpi-400
rpi-cm4
"

distro_variants="
base
cinnamon
gnome
kde
lxde
mate
server
xfce
"

for i in $distro_variants; do
	export SOLUTION=rpi64-$i
	echo "Generating distribution ..."
	aoscbootstrap \
		stable rpi64-${i} ${REPO:-https://repo.aosc.io/debs} \
		--config /usr/share/aoscbootstrap/config/aosc-mainline.toml \
		-x \
		--arch ${ARCH:-arm64} \
		-s \
		/usr/share/aoscbootstrap/scripts/reset-repo.sh \
		/usr/share/aoscbootstrap/scripts/enable-nvidia-drivers.sh \
		/usr/share/aoscbootstrap/scripts/enable-dkms.sh \
		/usr/share/aoscbootstrap/scripts/rawimage.sh \
		--include-files /usr/share/aoscbootstrap/recipes/rpi64/${i}-rpi64.lst
		-m bsp-rpi

	echo "Creating distribution tarball ..."
	tar cf rpi64-${i}.tar rpi64-${i}

	for j in $rpi64_devices_list; do
		echo "Generating raw image ..."
		TARBALL=$PWD/rpi64-${i}.tar DEVICE_NAME=$j ./raw-image-builder

	done
	echo "Removing generated distributions ..."
	rm -r rpi64-${i}.tar rpi64-${i}
done

for i in out/*.img; do
	echo "Compressing $i ..."
	lz4 -9 -vvv < $i > $i.lz4 && rm $i

	echo "Creating checksum for $i ..."
	sha256sum $i.lz4 > ${i}.lz4.sha256sum
done
