#!/bin/bash -e

starfive_devices_list="
jh7110-starfive-visionfive-2-v1.3b
"

starfive_devices_list_emmc="
jh7110-starfive-visionfive-2-v1.3b
"

starfive_devices_list_nvme="
jh7110-starfive-visionfive-2-v1.3b
"

distro_variants="
base
desktop
server
"

for i in $distro_variants; do
	export SOLUTION=starfive-$i
	for j in $starfive_devices_list; do
		echo "Generating distribution ..."
		aoscbootstrap \
			stable ${i}-${j} ${REPO:-https://repo.aosc.io/debs} \
			--config /usr/share/aoscbootstrap/config/aosc-mainline.toml \
			-x \
			--arch ${ARCH:-riscv64} \
			-s \
				/usr/share/aoscbootstrap/scripts/reset-repo.sh \
				/usr/share/aoscbootstrap/scripts/enable-nvidia-drivers.sh \
				/usr/share/aoscbootstrap/scripts/enable-dkms.sh \
				/usr/share/aoscbootstrap/scripts/rawimage.sh \
			--include-files /usr/share/aoscbootstrap/recipes/starfive/${i}-${j}.lst

		echo "Creating distribution tarball ..."
		tar cvf ${i}-${j}.tar ${i}-${j}

		echo "Generating raw image (SD card) ..."
		TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j STORAGE_TYPE=sd ./raw-image-builder
		if echo "$starfive_devices_list_emmc" | grep "^$j\$"; then
			echo "Generating raw image (eMMC) ..."
			TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j STORAGE_TYPE=emmc ./raw-image-builder
		fi
		if echo "$starfive_devices_list_nvme" | grep "^$j\$"; then
			echo "Generating raw image (NVME) ..."
			TARBALL=$PWD/${i}-${j}.tar DEVICE_NAME=$j STORAGE_TYPE=nvme ./raw-image-builder
		fi

		echo "Removing generated distributions ..."
		rm -r ${i}-${j}.tar ${i}-${j}
	done
done

for i in out/*.img; do
	echo "Compressing $i ..."
	lz4 -9 -vvv < $i > $i.lz4 && rm $i

	echo "Creating checksum for $i ..."
	sha256sum $i.lz4 > ${i}.lz4.sha256sum
done
