#! /bin/bash

rm -f out/* aux_log/*

sunxi64_devices_list="
sun50i-a64-pine64-plus
sun50i-a64-bananapi-m64
sun50i-h5-orangepi-pc2
sun50i-h5-orangepi-prime
sun50i-h5-nanopi-neo2
"

sunxi64_devices_list_emmc_mmc2="
sun50i-a64-bananapi-m64
"

export SOLUTION=sunxi64-base
# TARBALL environment variable is needed
for i in $sunxi64_devices_list
do
	DEVICE_NAME=$i ./raw-image-builder
	for j in out/*.img # Uncompressed ones
	do
		xz $XZFLAGS $j
		for k in md5 sha1 sha512
		do
			${k}sum $j.xz | awk '{print $1}' > $j.xz.${k}sum
		done
	done
done

for i in $sunxi64_devices_list_emmc_mmc2
do
	DEVICE_NAME=$i MMC=2 ./raw-image-builder
	for j in out/*.img # Uncompressed ones
	do
		xz $XZFLAGS $j
		for k in md5 sha1 sha512
		do
			${k}sum $j.xz | awk '{print $1}' > $j.xz.${k}sum
		done
	done
done
