#! /bin/bash

rm -f out/* aux_log/*

sunxi_devices_list="
sun4i-a10-cubieboard
sun7i-a20-cubietruck
sun7i-a20-bananapi-m1-plus

sun8i-h2-plus-orangepi-zero
sun8i-h3-orangepi-one
sun8i-h3-orangepi-plus
sun8i-h3-nanopi-neo
sun8i-h3-bananapi-m2-plus
sun8i-r40-bananapi-m2-ultra
"

sunxi_devices_list_emmc_mmc2="
sun8i-h3-orangepi-plus
sun8i-h3-bananapi-m2-plus
sun8i-r40-bananapi-m2-ultra
"

# STUB_TARBALL environment variable is needed
rm -rf cielfs
ciel init "$STUB_TARBALL"
# Workaround
mkdir -p cielfs/50-override/etc/systemd/
cat > cielfs/50-override/etc/systemd/resolved.conf << EOF
[Resolve]
DNS=114.114.114.114
DNSSEC=no
EOF
export SOLUTION=sunxi-base
for i in $sunxi_devices_list
do
	DEVICE_NAME=$i ciel generate sunxi-base
	TARBALL=temp.tar COMPRESSOR=cat ciel release sunxi_base_$i
	TARBALL=$PWD/temp.tar DEVICE_NAME=$i ./raw-image-builder
	rm temp.tar*
	for j in out/*.img # Uncompressed ones
	do
		lz4 < $j > $j.lz4 && rm $j
		for k in md5 sha1 sha512
		do
			${k}sum $j.lz4 | awk '{print $1}' > $j.lz4.${k}sum
		done
	done
done

for i in $sunxi_devices_list_emmc_mmc2
do
	DEVICE_NAME=$i ciel generate sunxi-base
	TARBALL=temp.tar COMPRESSOR=cat ciel release sunxi_base_$i
	TARBALL=$PWD/temp.tar DEVICE_NAME=$i MMC=2 ./raw-image-builder
	rm temp.tar*
	for j in out/*.img # Uncompressed ones
	do
		lz4 < $j > $j.lz4 && rm $j
		for k in md5 sha1 sha512
		do
			${k}sum $j.lz4 | awk '{print $1}' > $j.lz4.${k}sum
		done
	done
done
