#! /bin/bash -e

sunxi64_devices_list="
sun50i-a64-pinebook
sun50i-a64-pinephone
sun50i-a64-pinetab
sun50i-a64-teres-i
"

sunxi64_devices_list_emmc_mmc2="
sun50i-a64-pinebook
sun50i-a64-pinephone
sun50i-a64-pinetab
sun50i-a64-teres-i
"

export SOLUTION=sunxi64-gnome
for i in $sunxi64_devices_list
do
	# STUB_TARBALL environment variable is needed
	rm -rf .ciel resolved.conf.backup
	ciel init
	ciel load-os "$STUB_TARBALL"
	# Workaround
	cp .ciel/container/dist/etc/systemd/resolved.conf resolved.conf.backup
	cat > .ciel/container/dist/etc/systemd/resolved.conf << EOF
[Resolve]
DNS=114.114.114.114
DNSSEC=no
EOF
	if [ "$MIRROR" ]; then
		ciel switchmirror "$MIRROR"
	fi
	DEVICE_NAME=$i ciel generate sunxi64-gnome
	if [ "$MIRROR" ]; then
		ciel switchmirror origin
	fi
	ciel down
	cp resolved.conf.backup .ciel/container/dist/etc/systemd/resolved.conf 
	TARBALL=temp.tar COMPRESSOR=cat ciel release sunxi64_gnome_$i
	TARBALL=$PWD/temp.tar DEVICE_NAME=$i ./raw-image-builder
	if echo "$sunxi64_devices_list_emmc_mmc2" | grep "^$i\$"; then
		TARBALL=$PWD/temp.tar DEVICE_NAME=$i MMC=2 ./raw-image-builder
	fi
	rm temp.tar*
	for j in out/*.img # Uncompressed ones
	do
		lz4 < $j > $j.lz4 && rm $j
		for k in md5 sha1 sha512
		do
			${k}sum $j.lz4 | awk '{print $1}' > $j.lz4.${k}sum
		done
	done
done

rm -f resolved.conf.backup
